### ISSUE TITLE
Add option for show title

### ISSUE THREAD

**Issue by shopgirl284** [shopgirl284/Webisodes.bundle#4]
As per a user, look into an option for adding custom show titles. 

Adding an additional data field would require existing users to reenter all data and could cause the channel to give errors if they did not do this due to the structure of the channel data being different.

**Comment by ctindel** [comment]
There's no way to store a default or store custom metadata to do an if clause like "If user.title_override != NULL set title = user.title_override".  I'm obviously not familiar with plex plugins or your ability to do programmatic statements like this.

**Comment by shopgirl284** [comment]
This feature has been added to the channel
